image: mcr.microsoft.com/dotnet/core/sdk:2.2

stages:
  - build

before_script:
  - dotnet tool install fornax -g
  - export PATH="$PATH:/root/.dotnet/tools"

build:
  stage: build
  script:
  - fornax build