stages:
  - build
  - deploy
  - deploy_prod

build:
  stage: build
  image: paytonrules/fornax:0.2
  script: 
    - Fornax build
  artifacts:
    paths:
      - _public/

deploy_staging:
  stage: deploy
  image: paytonrules/netlify:0.1
  script:
    - netlify deploy --auth $NETLIFY_TOKEN --site=57098d77-10bb-4bf1-800b-767aae435879

deploy_production:
  stage: deploy_prod
  image: paytonrules/netlify:0.1
  when: manual
  script:
    - netlify deploy --prod --auth $NETLIFY_TOKEN --site=57098d77-10bb-4bf1-800b-767aae435879
