image: mcr.microsoft.com/dotnet/core/sdk:2.2

stages:
  - build

before_script:
  - export PATH="$PATH:/root/.dotnet/tools"
  - dotnet tool install fornax -g

build:
  stage: build
  script:
    - fornax build