stages:
  - build
  - deploy

build:
  stage: build
  image: mcr.microsoft.com/dotnet/core/sdk:2.2
  script:
    - export PATH="/root/.dotnet/tools:$PATH"
    - dotnet tool install fornax -g
    - Fornax build

deploy_staging:
  stage: deploy
  image: node:12-alpine
  script:
    - export NPM_CONFIG_PREFIX=/home/node/.npm-global
    - export PATH=$PATH:/home/node/.npm-global/bin
    - npm install -g netlify-cli
    - ls
    - netlify deploy --auth $NETLIFY_TOKEN