stages:
  - build
  - deploy

build:
  stage: build
  image: mcr.microsoft.com/dotnet/core/sdk:2.2
  script:
    - export PATH="/root/.dotnet/tools:$PATH"
    - dotnet tool install fornax -g
    - Fornax build

deploy_staging:
  stage: deploy
  image: nodejs:alpine
  script:
    - npm install -g netlify
    - netlify deploy --auth $NETLIFY_TOKEN