image: mcr.microsoft.com/dotnet/core/sdk:2.2

stages:
  - build

before_script:
  - export PATH="/root/.dotnet/tools:$PATH"
  - dotnet tool install fornax -g
  - ls /root/.dotnet/tools

build:
  stage: build
  script:
    - ls /root/.dotnet/tools
    - fornax build